### ISSUE TITLE
Why can the finger of gripper slip "into" the manipuland?

### ISSUE THREAD

**Issue by vinbo** [RussTedrake/underactuated#242]
In the problem set 5, this situation sometimes happens: one of the fingers may suddenly slip into the ball, like this
![planar_hand_ball](https://user-images.githubusercontent.com/29434082/71310967-7f03d880-2455-11ea-9e45-c02975470b19.gif)
Sometime it penetrates even deeper. I cannot understand why this happens. Any one has an answer? Thanks.

**Comment by gizatt** [comment]
Judging by the arrows, your contact forces are very high. The penetration looks sort of like simulation steps being too high for the contact forces you're applying -- you could either decrease the sim step rate or find a way to limit the applied forces.

**Comment by vinbo** [comment]
> 
> 
> Judging by the arrows, your contact forces are very high. The penetration looks sort of like simulation steps being too high for the contact forces you're applying -- you could either decrease the sim step rate or find a way to limit the applied forces.

Are you suggesting that the manipuland is not modeled as rigid body? Are you sure?

**Comment by gizatt** [comment]
Rigid body collisions are modeled as stiff springs when the bodies are interpenetrating -- see [here](https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_multibody_plant.html#mbp_penalty_method), or the more complete treatment [here](https://drake.mit.edu/doxygen_cxx/group__drake__contacts.html). Any luck with decreasing the simulation timestep or otherwise regulating your contact forces?

**Comment by RussTedrake** [comment]
Will close this due to inactivity.  Feel free to reopen if you think it is a real issue that warrants a resolution.
