### ISSUE TITLE
finalize directory structure

### ISSUE THREAD

**Issue by RussTedrake** [RussTedrake/underactuated#275]
With my decision to convert the examples from .py to .ipynb, the current directory structure needs some revision.  It is odd to have them in the underactuated module, when nobody can actually import from them, and odd to have a root "notebooks" directory that does not include these notebooks.

Proposal:
- `underactuated/notebooks/` => `underactuated/exercises`
- `underactuated/underactuated/*.ipynb` => `underactuated/examples`
- Files like `double_pendulum.urdf` or `quadrotor2d.py` would stay in `underactuated/underactuated` since they are resources that get found/imported from other places (esp the notebooks).  Not ideal that they become non-collocated, but I don't have a better suggestion.
- `figures/exercises` could move into `exercises`.  i'm more agnostic on this point.

@TobiaMarcucci -- can you help me summarize our thoughts here?

**Comment by TobiaMarcucci** [comment]
A consideration regarding the first point:
- The content of `underactuated/underactuated/exercises` should then move to `underactuated/exercises`, right? That folder is currently used only for the helpers of the exercise notebooks (urdfs and figures included). This will require to be able to import from `underactuated/exercises` directly.
- The `install.py` from the solutions repo will keep copying (and overwrite) only the notebooks to underactuated/exercises`, even if there will be other files there.
- We called `underactuated/notebooks` to mirror the solutions repo. I think it'd be odd to change `notebooks` <- `examples` also in the solutions (the only other folder is `written`). Should we break this symmetry?

I agree with the second and third points.

For the last point I'd keep `figures/exercises` where it is, since these are figures of the textbook and not of the exercise notebooks.
