### ISSUE TITLE
Link to PDF Files in Bibliography

### ISSUE THREAD

**Issue by TVarkey** [RussTedrake/underactuated#30]
Hi,
Link to PDF Files in Bibliography returns 404.
http://groups.csail.mit.edu/robotics-center/papers/Asada86.pdf
Could someone update the website to add the directory?
Thanks

**Comment by RussTedrake** [comment]
I'm afraid those links were never active for outside MIT.   they are generated from a simple script that doesn't understand the difference.  

Note that a few of the pdfs (including all of the ones written by me and my students) will work, because i am legally allowed to redistribute them.

I will leave this issue open as a reminder to update the script.

**Comment by RussTedrake** [comment]
have updated the script.
